kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  label:
    app: helloworld-go
  name: helloworld-go
  labels:
    build: helloworld-go
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'hello-openshift:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/grebane/openshift-olm-apps/tree/master/sample-app"

---

  kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: helloworld-go
    labels:
      app: helloworld-go
  spec:
    lookupPolicy:
      local: false